version: 2.1

commands:
  debugit:
    steps:
      - run: docker image ls
      - run: docker buildx ls

jobs:
  docker_build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - debugit
      # - run:
      #     name: build image with docker
      #     command: |
      #       docker build -t test1 .
      - run:
          name: install arm build support into remote-docker instance
          command: |
            ssh remote-docker "sudo apt-get update; sudo apt-get install -y qemu-user-static binfmt-support; qemu-aarch64-static --version"
      - debugit
      - run:
          name: build image for amd64
          command: |
            docker buildx build --platform linux/amd64,linux/arm64 -t test1-amd64 .
      - debugit
      # - run:
      #     name: build image for arm64
      #     command: |
      #       docker buildx build --platform linux/arm64 -t test1-arm64 .
      - debugit

workflows:
  build:
    jobs:
      - docker_build
